name: FlashLoan CI

on: 
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    environment: devnet
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@master
      
      - name: Compile Contracts
        run: forge build
        working-directory: contracts

      - name: Install cast/wallet
        run: sudo apt-get install -y jq

      - name: Read secret
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: echo "$PRIVATE_KEY"
      # - name: Deploy and Fund
      #   env:
      #     PRIVATE_KEY: ${{ secrets.PK }}
      #   run: bash deploy.sh $PRIVATE_KEY
      #   working-directory: contracts

      # - name: Run Tests
      #   run: bash test.sh
      #   working-directory: contracts
